CREATE TABLE `Musician` 
(
    MusicianId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MusicianName VARCHAR(50) NOT NULL,
    Password VARCHAR(150) NOT NULL,
    FirstName VARCHAR(30) NOT NULL,
    LastName VARCHAR(30) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Country VARCHAR(30) NOT NULL,
    RegDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);